name: refine-postgres-example
channels:
  - defaults
dependencies:
  - postgresql
  - psycopg2
  - pip:
    - pandas
    - git+https://github.com/catherinedevlin/ipython-sql.git
    - git+https://github.com/jupyterhub/jupyter-server-proxy
    - git+https://github.com/dbutlerdb/refine-client-py
