#!/bin/bash
set -e

wget -q -O openrefine-2.8.tar.gz https://github.com/OpenRefine/OpenRefine/releases/download/2.8/openrefine-linux-2.8.tar.gz
mkdir -p $HOME/.openrefine
tar xzf openrefine-2.8.tar.gz -C $HOME/.openrefine
rm openrefine-2.8.tar.gz

mkdir -p $HOME/openrefine
