#!/bin/bash
set -eux

#So what's the approved route for running things in the background?
#Maybe I was getting the path wrong?
#nohup  jupyter kernelgateway --KernelGatewayApp.api='kernel_gateway.notebook_http' --KernelGatewayApp.seed_uri='/home/jovyan/notebooks/Reconciler.ipynb' --port 8895 >/dev/null 2>&1


exec "$@"
